version: '3'
volumes:
  data:
services:
  db:
    image: mysql:${VERSION}
    ports:
      - "${PORT_EX}:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
